# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingswidget.ui'
#
# Created by: PyQt5 UI code generator 5.7.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(501, 285)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gbxFilterPackages = QtWidgets.QTabWidget(SettingsWidget)
        self.gbxFilterPackages.setObjectName("gbxFilterPackages")
        self.tabFilterPackages = QtWidgets.QWidget()
        self.tabFilterPackages.setObjectName("tabFilterPackages")
        self.gridLayout = QtWidgets.QGridLayout(self.tabFilterPackages)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFilterPackageAdd = QtWidgets.QPushButton(self.tabFilterPackages)
        self.btnFilterPackageAdd.setObjectName("btnFilterPackageAdd")
        self.horizontalLayout.addWidget(self.btnFilterPackageAdd)
        self.btnFilterPackageRemove = QtWidgets.QPushButton(self.tabFilterPackages)
        self.btnFilterPackageRemove.setObjectName("btnFilterPackageRemove")
        self.horizontalLayout.addWidget(self.btnFilterPackageRemove)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.lstFilterPackages = QtWidgets.QTreeView(self.tabFilterPackages)
        self.lstFilterPackages.setIndentation(0)
        self.lstFilterPackages.setObjectName("lstFilterPackages")
        self.gridLayout.addWidget(self.lstFilterPackages, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnFilterPackageMoveUp = QtWidgets.QToolButton(self.tabFilterPackages)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFilterPackageMoveUp.sizePolicy().hasHeightForWidth())
        self.btnFilterPackageMoveUp.setSizePolicy(sizePolicy)
        self.btnFilterPackageMoveUp.setObjectName("btnFilterPackageMoveUp")
        self.verticalLayout_3.addWidget(self.btnFilterPackageMoveUp)
        self.btnFilterPackageMoveDown = QtWidgets.QToolButton(self.tabFilterPackages)
        self.btnFilterPackageMoveDown.setObjectName("btnFilterPackageMoveDown")
        self.verticalLayout_3.addWidget(self.btnFilterPackageMoveDown)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.gbxFilterPackages.addTab(self.tabFilterPackages, "")
        self.tabUpdates = QtWidgets.QWidget()
        self.tabUpdates.setObjectName("tabUpdates")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabUpdates)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.chkUpdates = QtWidgets.QCheckBox(self.tabUpdates)
        self.chkUpdates.setObjectName("chkUpdates")
        self.verticalLayout_4.addWidget(self.chkUpdates)
        self.chkDevelUpdates = QtWidgets.QCheckBox(self.tabUpdates)
        self.chkDevelUpdates.setObjectName("chkDevelUpdates")
        self.verticalLayout_4.addWidget(self.chkDevelUpdates)
        self.btnCheckNow = QtWidgets.QPushButton(self.tabUpdates)
        self.btnCheckNow.setObjectName("btnCheckNow")
        self.verticalLayout_4.addWidget(self.btnCheckNow)
        spacerItem1 = QtWidgets.QSpacerItem(20, 87, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.gbxFilterPackages.addTab(self.tabUpdates, "")
        self.verticalLayout_2.addWidget(self.gbxFilterPackages)
        self.btns = QtWidgets.QDialogButtonBox(SettingsWidget)
        self.btns.setOrientation(QtCore.Qt.Horizontal)
        self.btns.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btns.setObjectName("btns")
        self.verticalLayout_2.addWidget(self.btns)

        self.retranslateUi(SettingsWidget)
        self.gbxFilterPackages.setCurrentIndex(0)
        self.btns.accepted.connect(SettingsWidget.accept)
        self.btns.rejected.connect(SettingsWidget.reject)
        self.chkUpdates.toggled['bool'].connect(self.chkDevelUpdates.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        SettingsWidget.setWindowTitle(_translate("SettingsWidget", "Settings"))
        self.btnFilterPackageAdd.setText(_translate("SettingsWidget", "Add filter package ..."))
        self.btnFilterPackageRemove.setText(_translate("SettingsWidget", "Forget package"))
        self.btnFilterPackageMoveUp.setText(_translate("SettingsWidget", "Up"))
        self.btnFilterPackageMoveDown.setText(_translate("SettingsWidget", "Down"))
        self.gbxFilterPackages.setTabText(self.gbxFilterPackages.indexOf(self.tabFilterPackages), _translate("SettingsWidget", "Filter Packages"))
        self.chkUpdates.setText(_translate("SettingsWidget", "Check for software updates"))
        self.chkDevelUpdates.setText(_translate("SettingsWidget", "Include development (beta) versions"))
        self.btnCheckNow.setText(_translate("SettingsWidget", "Check Now"))
        self.gbxFilterPackages.setTabText(self.gbxFilterPackages.indexOf(self.tabUpdates), _translate("SettingsWidget", "Software Updates"))

