# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingswidget.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWidget(object):
    def setupUi(self, SettingsWidget):
        SettingsWidget.setObjectName("SettingsWidget")
        SettingsWidget.resize(409, 417)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(SettingsWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wGeneral = QtWidgets.QGroupBox(SettingsWidget)
        self.wGeneral.setObjectName("wGeneral")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wGeneral)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.spnMaxRecentFiles = QtWidgets.QSpinBox(self.wGeneral)
        self.spnMaxRecentFiles.setMaximum(31)
        self.spnMaxRecentFiles.setObjectName("spnMaxRecentFiles")
        self.gridLayout_2.addWidget(self.spnMaxRecentFiles, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.wGeneral)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.chkHideStartupWindow = QtWidgets.QCheckBox(self.wGeneral)
        self.chkHideStartupWindow.setObjectName("chkHideStartupWindow")
        self.gridLayout_2.addWidget(self.chkHideStartupWindow, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.wGeneral)
        self.groupBox = QtWidgets.QGroupBox(SettingsWidget)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.chkGithubAuth = QtWidgets.QCheckBox(self.groupBox)
        self.chkGithubAuth.setObjectName("chkGithubAuth")
        self.gridLayout_3.addWidget(self.chkGithubAuth, 0, 0, 1, 2)
        self.lblGithubAuthStatus = QtWidgets.QLabel(self.groupBox)
        self.lblGithubAuthStatus.setTextFormat(QtCore.Qt.RichText)
        self.lblGithubAuthStatus.setObjectName("lblGithubAuthStatus")
        self.gridLayout_3.addWidget(self.lblGithubAuthStatus, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.groupBox)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.groupBox_2 = QtWidgets.QGroupBox(SettingsWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnFilterPackageAdd = QtWidgets.QPushButton(self.groupBox_2)
        self.btnFilterPackageAdd.setObjectName("btnFilterPackageAdd")
        self.horizontalLayout.addWidget(self.btnFilterPackageAdd)
        self.btnFilterPackageRemove = QtWidgets.QPushButton(self.groupBox_2)
        self.btnFilterPackageRemove.setObjectName("btnFilterPackageRemove")
        self.horizontalLayout.addWidget(self.btnFilterPackageRemove)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)
        self.lstFilterPackages = QtWidgets.QTreeView(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lstFilterPackages.sizePolicy().hasHeightForWidth())
        self.lstFilterPackages.setSizePolicy(sizePolicy)
        self.lstFilterPackages.setIndentation(0)
        self.lstFilterPackages.setObjectName("lstFilterPackages")
        self.gridLayout.addWidget(self.lstFilterPackages, 0, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.btnFilterPackageMoveUp = QtWidgets.QToolButton(self.groupBox_2)
        self.btnFilterPackageMoveUp.setObjectName("btnFilterPackageMoveUp")
        self.verticalLayout_3.addWidget(self.btnFilterPackageMoveUp)
        self.btnFilterPackageMoveDown = QtWidgets.QToolButton(self.groupBox_2)
        self.btnFilterPackageMoveDown.setObjectName("btnFilterPackageMoveDown")
        self.verticalLayout_3.addWidget(self.btnFilterPackageMoveDown)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_3.addItem(spacerItem1)
        self.gridLayout.addLayout(self.verticalLayout_3, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.btns = QtWidgets.QDialogButtonBox(SettingsWidget)
        self.btns.setOrientation(QtCore.Qt.Horizontal)
        self.btns.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.btns.setObjectName("btns")
        self.verticalLayout_2.addWidget(self.btns)

        self.retranslateUi(SettingsWidget)
        self.btns.accepted.connect(SettingsWidget.accept)
        self.btns.rejected.connect(SettingsWidget.reject)
        QtCore.QMetaObject.connectSlotsByName(SettingsWidget)

    def retranslateUi(self, SettingsWidget):
        _translate = QtCore.QCoreApplication.translate
        SettingsWidget.setWindowTitle(_translate("SettingsWidget", "Settings"))
        self.wGeneral.setTitle(_translate("SettingsWidget", "General"))
        self.label.setText(_translate("SettingsWidget", "Remember recent files:"))
        self.chkHideStartupWindow.setText(_translate("SettingsWidget", "Hide startup window after opening a document"))
        self.groupBox.setTitle(_translate("SettingsWidget", "Github: Access Remote Filter Packages"))
        self.chkGithubAuth.setText(_translate("SettingsWidget", "Use authentication (e.g. access private repositories)"))
        self.lblGithubAuthStatus.setText(_translate("SettingsWidget", "&lt;auth status here...>"))
        self.groupBox_2.setTitle(_translate("SettingsWidget", "Filter packages"))
        self.btnFilterPackageAdd.setText(_translate("SettingsWidget", "Add filter package ..."))
        self.btnFilterPackageRemove.setText(_translate("SettingsWidget", "Forget package"))
        self.btnFilterPackageMoveUp.setText(_translate("SettingsWidget", "▲"))
        self.btnFilterPackageMoveDown.setText(_translate("SettingsWidget", "▼"))


