################################################################################
#                                                                              #
#   This file is part of the Bibolamazi Project.                               #
#   Copyright (C) 2013 by Philippe Faist                                       #
#   philippe.faist@bluewin.ch                                                  #
#                                                                              #
#   Bibolamazi is free software: you can redistribute it and/or modify         #
#   it under the terms of the GNU General Public License as published by       #
#   the Free Software Foundation, either version 3 of the License, or          #
#   (at your option) any later version.                                        #
#                                                                              #
#   Bibolamazi is distributed in the hope that it will be useful,              #
#   but WITHOUT ANY WARRANTY; without even the implied warranty of             #
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the              #
#   GNU General Public License for more details.                               #
#                                                                              #
#   You should have received a copy of the GNU General Public License          #
#   along with Bibolamazi.  If not, see <http://www.gnu.org/licenses/>.        #
#                                                                              #
################################################################################

import re
import os
import os.path
import io
from urllib2 import HTTPError

from pybtex.database import BibliographyData;
import pybtex.database.input.bibtex as inputbibtex;

from core.bibfilter import BibFilter, BibFilterError, CommaStrList;
from core.blogger import logger;

import arxiv2bib
from .util import arxivutil

from .util import auxfile


HELP_AUTHOR = u"""\
Cite Arxiv IDs filter by Philippe Faist, (C) 2013, GPL 3+ (with code from Nathan Grigg (C) new BSD license)
"""

HELP_DESC = u"""\
Filter that fills BibTeX files with relevant entries to cite with \cite{1211.1037}
"""

HELP_TEXT = u"""
This filter scans a LaTeX document for citations of the form `\cite{XXXX.XXXX}' or
`\cite{archive/XXXXXXX}', and adds the corresponding bibtex items in the combined bibtex
database with the arXiv ID as citation key. The bibtex entry is generated by querying the
arXiv API; you of course need internet access for this.

You should provide the base file name of the LaTeX document, e.g. if your document is
named `mydoc.tex', then you should specify the option `-sJobname=mydoc'. Note that the AUX
file (`mydoc.aux') is actually scanned, and not the LaTeX document itself; this means that
you need to run (Pdf)LaTeX *before* running bibolamazi.

If the `mydoc.aux' file is in a different directory than the bibolamazi file, you may
specify where to look for the aux file with the option `-sSearchDirs=...'.

If the option `-dJournalRefInNote' is provided, then the journal reference, as returned by
the arXiv query and if existing, is added in the `note={}' field of the bibtex entry.


Note: this filter uses some 3rd party code (arxiv2bib) by Nathan Grigg available at
  https://github.com/nathangrigg/arxiv2bib
and licensed under the new BSD license.

"""



class CiteArxivFilter(BibFilter):

    helpauthor = HELP_AUTHOR
    helpdescription = HELP_DESC
    helptext = HELP_TEXT

    def __init__(self, jobname, search_dirs=[], journal_ref_in_note=False):
        """CiteArxivFilter constructor.

        Arguments:
          - jobname: the base name of the latex file. Will search for jobname.aux and look
              for `\citation{..}' commands as they are generated by latex.
          - search_dirs(CommaStrList): the .aux file will be searched for in this list of
              directories; separate directories with commas e.g. 'path/to/dir1,path/to/dir2'
              (escape commas and backslashes with a backslash)
          - journal_ref_in_note(bool): keep the journal reference given by the arXiv in the
              note={} bibtex field. (default: No)
        """

        BibFilter.__init__(self);

        self.jobname = jobname
        self.search_dirs = search_dirs
        self.journal_ref_in_note = journal_ref_in_note;

        if (not self.search_dirs):
            self.search_dirs = ['.', '_cleanlatexfiles'] # also for my cleanlatex utility :)

        logger.debug('citearxiv: jobname=%r' % (jobname,));


    def name(self):
        return "citearxiv"

    def getRunningMessage(self):
        return u"citearxiv: parsing & fetching relevant arxiv citations ..."

    
    def action(self):
        return BibFilter.BIB_FILTER_BIBOLAMAZIFILE;


    def filter_bibolamazifile(self, bibolamazifile):

        arxiv_fetched_cache = self.cache_for('arxiv_fetched_api_info')['fetched'];
        citearxiv_cachebase = self.cache_for('citearxiv_uselist');
        citearxiv_cachebase.setdefault('idlist', [])
        citearxiv_uselist = citearxiv_cachebase['idlist'];

        logger.longdebug('fetched arxiv citations cache: %r: %r' %(arxiv_fetched_cache.keys(),
                                                                   arxiv_fetched_cache))

        #
        # find and analyze jobname.aux. Look for \citation{...}'s and collect them.
        #

        def add_to_cite_list(citekey):
            if (not arxiv2bib.NEW_STYLE.match(citekey) and
                not arxiv2bib.OLD_STYLE.match(citekey)):
                # this is not an arxiv citation key
                return

            # citekey is an arxiv ID
            arxivid = citekey;
            if (arxivid not in citearxiv_uselist):
                citearxiv_uselist.append(arxivid)
                
        auxfile.get_all_auxfile_citations(self.jobname, bibolamazifile,
                                          filtername=self.name(),
                                          search_dirs=self.search_dirs,
                                          return_set=False,
                                          callback=add_to_cite_list,
                                          )
        
        #
        # Now, fetch all bib entries that we need.
        #

        missing_ids = []
        for arxivid in citearxiv_uselist:
            if arxivid not in arxiv_fetched_cache:
                missing_ids.append(arxivid)

        # if there are missing ids, fetch them
        if (missing_ids):
            arxivutil.fetch_arxiv_api_info(missing_ids, arxiv_fetched_cache, self)

        logger.longdebug('fetched arxiv citations cache: %r' %(arxiv_fetched_cache))

        #
        # Now, include all the entries of arxiv_fetched_cache into our database.
        #
        # Variable bibdata is a pybtex.database.BibliographyData object
        #

        thebibdata = bibolamazifile.bibliographydata();

        # join all the bibtex blocks of all the cached entries
        allbibtex = "\n".join( [ val['bibtex'] for k,val in arxiv_fetched_cache.iteritems() ] );

        for arxivid in citearxiv_uselist:
            dat = arxiv_fetched_cache.get(arxivid)
            if (dat is None):
                errref = arxiv2bib.ReferenceErrorInfo('ArXiv info for `%s''not in cache' %(arxivid),
                                                      arxivid)
                dat = {'reference': errref,
                       'bibtex': errref.bibtex(),
                       }

            # parse bibtex
            parser = inputbibtex.Parser();
            new_bib_data = None;
            with io.StringIO(unicode(dat['bibtex'])) as stream:
                new_bib_data = parser.parse_stream(stream);
            
            # and add them to the main list
            if (len(new_bib_data.entries.keys()) != 1):
                logger.warning("Got more than one bibtex entry when retreiving `%s'!" %(arxivid))

            for val in new_bib_data.entries.values():
                if (not self.journal_ref_in_note and 'note' in val.fields):
                    del val.fields['note'];
                thebibdata.add_entry(arxivid, val);

        #
        # yay, done!
        #
        
        return


def bibolamazi_filter_class():
    return CiteArxivFilter;

